# Site settings
title: ArgumentException
email: spiros@sdellaportas.com
description: > # this means to ignore newlines until "baseurl:"
  I am Spiros Dellaportas, a Software Craftsman living in London, this is my personal blog. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sdellaportas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
